# Site settings
email: deonquebec@gmail.com
baseurl: "/blog"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Daehyun's Blog
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: 
#profile_img: black_background_wood-wallpaper-1920x1200.jpg
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
