# Site settings
email: 
baseurl: "/blog"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: dqgthb's Blog
description: Hello world! This is SEO description. 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: "https://octodex.github.com/images/Professortocat_v2.png"
profile: "dqgthb is an abbreviation for 'Mr D lives in region Q and loves github'. \r Nice to meet you!"
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
